package com.mathiric.myproductd;

public class Rspec6207 {
}

record OtherPerson(String name, int age) {
    OtherPerson { // Noncompliant, no need for empty compact constructor
    }
    public String name() { // Noncompliant, already autogenerated
        return name;
    }
}
